// Encabezados EXACTOS de la plantilla original (incluye espacios/tildes tal cual)
// para garantizar que el Excel exportado sea idéntico al de la plantilla.
module.exports = {
  PLANEACION: [
    "LLAVE","CODIGO","FACULTAD","PROGRAMA  ","PLAN","ASIGNATURA","CICLO","CREDITOS",
    "GRUPO","CODIGO MOODLE","CODIGO TEAMS","ENLACE TEAMS","ESTADO","MODALIDAD","JORNADA ",
    "CAPACIDAD","LUN H INICIAL","LUN HORA FINAL","LUN SALON","MAR H INICIAL2",
    "MAR HORA FINAL3","MAR SALON","MCL HORA INICIAL","MCL HORA FINAL6","MCL SALON",
    "JUE HORA INICIAL2","JUE HORA FINAL63","JUE SALON","VIE HORA INICIAL22",
    "VIE HORA FINAL633","VIE SALON4","DOCUMENTO_DOCENTE","NOMBRE_DOCENTE",
    "CORREO INSTITUCIONAL ","CODIGO MOODLE A DUPLICAR"," PERIODO ","FECHA MODIFICACION",
    " MODIFICACION  "," OBSERVACIONES ","LLAVE HORARIOS","ID REFLEJO"
  ],
  DOCENTES: ["NIT_CC","NOMBRE_COMPLETO","CORREO INSTITUCIONAL","FACULTAD","SEDE"],
  // Hojas que se conservan vacías/tal cual en el archivo final (no forman parte
  // del flujo de captura de esta aplicación, pero se incluyen para que el
  // archivo entregado tenga la misma estructura de pestañas que la plantilla).
  REFLEJOS: [
    "Llave","Hora de inicio","Hora de finalización","Correo electrónico","Nombre",
    "CÓDIGO ASIGNATURA NO OFERTADA (NÚMERO DE 4 DÍGITOS)","PROGRAMA NO OFERTADA",
    "PLAN DE ESTUDIOS NO OFERTADA","NOMBRE ASIGNATURA NO OFERTADA",
    "CICLO ASIGNATURA NO OFERTADA","NÚMERO DE CRÉDITOS ASIGNATURA NO OFERTADA",
    "CÓDIGO ASIGNATURA VIGENTE","PROGRAMA ASIGNATURA VIGENTE","ASIGNATURA VIGENTE",
    "GRUPO ASIGNATURA VIGENTE","ESTADO","CREACIÓN REFLEJO ","CODIGO MOODLE",
    "CODIGO TEAMS","ENLACE TEAMS","MODALIDAD","JORNADA ","DÍA","H_INICIO","H_FIN",
    "NOMBRE_SALON","DOCUMENTO_DOCENTE","NOMBRE_DOCENTE","CORREO INSTITUCIONAL ",
    "FECHAS DE REFLEJOS MODALIDAD VIRTUAL"
  ],
  CERRADOS: [
    "LLAVE","CODIGO","FACULTAD","PROGRAMA  ","PLAN","ASIGNATURA","CICLO","CREDITOS",
    "GRUPO","CODIGO MOODLE","CODIGO TEAMS","ENLACE TEAMS","ESTADO","MODALIDAD",
    "JORNADA ","CAPACIDAD","DIA","H_INICIO","H_FIN","NOMBRE_SALON","DOCUMENTO_DOCENTE",
    "NOMBRE_DOCENTE","CORREO INSTITUCIONAL ","CODIGO MOODLE A DUPLICAR"," PERIODO ",
    "FECHA MODIFICACION"," MODIFICACION  "," OBSERVACIONES ","LLAVE HORARIOS","ID REFLEJO"
  ]
};
